docs: refactor documentation
Security-Tools-Alliance/rengine-ng pull request #115
Opened 2024-06-22 13:59 UTC by AnonymousWP

- [docs: delete CODE_OF_CONDUCT.md](https://github.com/Security-Tools-Alliance/rengine-ng/commit/8c697d08a09e5eefea7db729530b4743f8b88a3b)
- [docs: delete FUNDING.yml](https://github.com/Security-Tools-Alliance/rengine-ng/commit/3867816ce4597c032f0f8cdb40a402fd028ad8d9)
- [docs: delete SECURITY.md](https://github.com/Security-Tools-Alliance/rengine-ng/commit/06a0ff095730c285c8a6a27fab5c5ad525a0cadb)
- [docs: delete SPONSORS.md](https://github.com/Security-Tools-Alliance/rengine-ng/commit/ed43e57c125f92fd8d077c1f9f9f1719122744c7)
- [docs(contributors): move content to README](https://github.com/Security-Tools-Alliance/rengine-ng/commit/898bc4c568bdc318ed5d284ca5f101d7e4531990)
- [build(ci): delete auto-comment.yml](https://github.com/Security-Tools-Alliance/rengine-ng/commit/8c008a4c96b622d0023575868d0832fdee97ce18)

2024-07-02 12:44 UTC, AnonymousWP commented
@psyray I think most of it is done, but there are still quite some things in the Wiki and README we can / need to finetune. Perhaps we can do a call to quickly talk about it sometime this week. Feel free to review it already, but let's wait with merging before we have decided about the documentation.

2024-07-02 23:10 UTC, psyray requested changes

2024-07-02 23:10 UTC, psyray commented on web/templates/base/login.html
> +              <span>If you have any issues or feature request, feel free to <a href="https://github.com/Security-Tools-Alliance/reNgine-ng/issues" class="text-primary">raise issue on Github.</a></spa
not necessary to change here, link is valid but real url is in lowercase

2024-07-08 17:38 UTC, AnonymousWP commented
The only thing that's left is the to-do list we talked about: https://github.com/Security-Tools-Alliance/rengine-ng/issues/5#issuecomment-2204495813. Working on that now.

2024-07-19 09:02 UTC, psyray submitted a review, later dismissed

2024-07-23 16:31 UTC, psyray approved these changes

2024-07-23 16:32 UTC, merged