feat: enhance LLM model selection and attack surface analysis
Security-Tools-Alliance/rengine-ng pull request #233
Opened 2024-11-11 12:23 UTC by psyray

- Introduced a new modal for selecting LLM models for attack surface analysis, allowing users to choose from a list of available models.
- Added functionality to update the selected model in the database before proceeding with analysis.
- Implemented a new API endpoint to fetch available LLM models and the currently selected model.
- Refactored the show_attack_surface_modal function to include model selection and handle errors more robustly.
- Removed hardcoded LLM definitions and prompts from definitions.py and moved them to a new configuration file.
- Added new classes and methods for managing LLM configurations and generating vulnerability reports and attack suggestions.
- Updated tests to cover new functionalities and removed obsolete tests related to LLM attack suggestions.

2024-11-12 22:45 UTC, psyray commented on web/static/custom/custom.js
> +	$('#modal_dialog .modal-text').append(
Will fix this later in a security review

2024-11-12 22:46 UTC, psyray commented on web/api/views.py
> +            except Exception as e:
not related to this PR

2024-11-12 22:46 UTC, psyray commented on web/api/views.py
> +                    print(e)
Not related to this PR

2024-11-12 22:46 UTC, psyray commented on web/api/views.py
> +                'message': str(e)
Will fix this later in a security review

2024-11-12 22:49 UTC, psyray commented
Too many sourcery review here.
Because it scan all the modified files.
It's not related to this PR.
Will fix this later in a security review

2024-11-13 23:14 UTC, AnonymousWP requested changes
Didn't have time yet to do an extensive test, but this is what I initially found. Will continue tomorrow.

2024-11-13 23:14 UTC, AnonymousWP commented on web/scanEngine/templates/scanEngine/settings/llm_toolkit.html
Please either remove the 3 dots or make it possible to delete external (non-local) LLMs like ChatGPT.

2024-11-14 13:04 UTC, psyray commented on web/scanEngine/templates/scanEngine/settings/llm_toolkit.html
Those external models are not deletable for the moment because they're harcoded in the config file
https://github.com/Security-Tools-Alliance/rengine-ng/blob/f5f37f4f0984e7a3d2f6a00b93edbb4ee5b7b1ed/web/reNgine/llm/config.py#L146-L183
https://github.com/Security-Tools-Alliance/rengine-ng/blob/f5f37f4f0984e7a3d2f6a00b93edbb4ee5b7b1ed/web/reNgine/llm/config.py#L101-L114

So, as it's not in the database it's not deletable.
Maybe I will implement this in future version, but I don't have the time to do this now.

Anyway I will remove the 3 dots on a selected model because the menu is empty on this kind of model

2024-11-14 13:12 UTC, psyray commented on web/scanEngine/templates/scanEngine/settings/llm_toolkit.html
Done

2025-05-22 11:59 UTC, merged