feat(install): arm64 support
Security-Tools-Alliance/rengine-ng pull request #82
Opened 2024-05-21 21:05 UTC by yarysp

This PR brings the ARM64 arch build official !

I've also improved the docker generation and the install script based on the @vncloudsco, @4NK1T & @sa7mon PR proposed on reNgine
https://github.com/yogeshojha/rengine/pull/1007
https://github.com/yogeshojha/rengine/pull/1212
https://github.com/yogeshojha/rengine/pull/1210

2024-05-24 11:05 UTC, AnonymousWP commented
I think you need to rebase this one due to the recent merge of https://github.com/Security-Tools-Alliance/rengine-ng/pull/81.

2024-05-24 11:12 UTC, yarysp commented
> I think you need to rebase this one due to the recent merge of #81.

Yes but release/2.1.0 needs to be rebased first

2024-05-27 14:25 UTC, AnonymousWP requested changes

2024-05-27 14:25 UTC, AnonymousWP commented on web/Dockerfile
> +    name="reNgine NG" \
```suggestion
    name="reNgine-ng" \
```

2024-05-27 14:25 UTC, AnonymousWP commented on web/Dockerfile
> +    description="reNGine NG is a automated pipeline of recon process, useful for information gathering during web application penetration testing."
```suggestion
    description="reNgine-ng is a automated pipeline of recon process, useful for information gathering during web application penetration testing."
```

2024-06-03 14:10 UTC, merged